In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path

In [2]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)

In [3]:
DATA = Path("../../data")

In [4]:
train_data = pd.read_csv(DATA / "train.csv")

In [5]:
train_data.head(50)

id class  cap-diameter cap-shape cap-surface cap-color does-bruise-or-bleed gill-attachment gill-spacing gill-color  stem-height  stem-width stem-root stem-surface stem-color veil-type veil-color has-ring ring-type spore-print-color habitat season
0    0     e          8.80         f           s         u                    f               a            c          w         4.51       15.39       NaN          NaN          w       NaN        NaN        f         f               NaN       d      a
1    1     p          4.51         x           h         o                    f               a            c          n         4.79        6.48       NaN            y          o       NaN        NaN        t         z               NaN       d      w
2    2     e          6.94         f           s         b                    f               x            c          w         6.85        9.93       NaN            s          n       NaN        NaN        f         f               NaN       l      w
3    3     e          3.88         f           y         g                    f               s          NaN          g         4.16        6.53       NaN          NaN          w       NaN        NaN        f         f               NaN       d      u
4    4     e          5.85         x           l         w                    f               d          NaN          w         3.37        8.36       NaN          NaN          w       NaN        NaN        f         f               NaN       g      a
5    5     p          4.30         x           t         n                    f               s            c          n         5.91        8.20       NaN          NaN          w       NaN          n        t         z               NaN       d      a
6    6     e          9.65         p           y         w                    f               e            c          k        19.07       12.69       NaN            s          w       NaN        NaN        t         e               NaN       g      w
7    7     p          4.55         x           e         e                    f               a          NaN          y         8.31        9.77       NaN          NaN          y       NaN          w        t         z               NaN       d      a
8    8     p          7.36         f           h         e                    f               x            d          w         5.77       17.13         b          NaN          w       NaN        NaN        f         f               NaN       d      a
9    9     e          6.45         x           t         n                    f               a            d          w         7.13       12.77       NaN          NaN          e       NaN        NaN        f         f               NaN       d      a
10  10     e          7.49         f           t         n                    f               s          NaN          n         9.14       13.00       NaN            t          o       NaN        NaN        f         f               NaN       d      a
11  11     e          8.30         x           y         n                    f             NaN          NaN          w         6.56       24.11         b          NaN          n       NaN          w        t         e               NaN       d      w
12  12     e          2.74         b           g         n                    f               a            d          g         4.33        2.57       NaN            s          n       NaN        NaN        f         f               NaN       d      s
13  13     e          6.53         x           y         n                    f               e            c          w         6.37       10.29       NaN            y          n       NaN        NaN        f         f               NaN       d      a
14  14     p          3.91         b           t         n                    f             NaN          NaN          n         9.81        5.55       NaN          NaN          w       NaN        NaN        t       NaN      

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3116945 entries, 0 to 3116944
Data columns (total 22 columns):
 #   Column                Dtype  
---  ------                -----  
 0   id                    int64  
 1   class                 object 
 2   cap-diameter          float64
 3   cap-shape             object 
 4   cap-surface           object 
 5   cap-color             object 
 6   does-bruise-or-bleed  object 
 7   gill-attachment       object 
 8   gill-spacing          object 
 9   gill-color            object 
 10  stem-height           float64
 11  stem-width            float64
 12  stem-root             object 
 13  stem-surface          object 
 14  stem-color            object 
 15  veil-type             object 
 16  veil-color            object 
 17  has-ring              object 
 18  ring-type             object 
 19  spore-print-color     object 
 20  habitat               object 
 21  season                object 
dtypes: float64(3), int64(1), object(18)
memory

In [7]:
train_data.isna().sum()

id                            0
class                         0
cap-diameter                  4
cap-shape                    40
cap-surface              671023
cap-color                    12
does-bruise-or-bleed          8
gill-attachment          523936
gill-spacing            1258435
gill-color                   57
stem-height                   0
stem-width                    0
stem-root               2757023
stem-surface            1980861
stem-color                   38
veil-type               2957493
veil-color              2740947
has-ring                     24
ring-type                128880
spore-print-color       2849682
habitat                      45
season                        0
dtype: int64

In [8]:
for column in train_data.columns[1:]:
    print(f"== {column} ==")
    print(f"{train_data[column].unique()}")

== class ==
['e' 'p']
== cap-diameter ==
[ 8.8   4.51  6.94 ... 38.11 55.63 54.07]
== cap-shape ==
['f' 'x' 'p' 'b' 'o' 'c' 's' 'd' 'e' 'n' nan 'w' 'k' 'l' '19.29' '5 f' 't'
 'g' 'z' 'a' '2.85' '7 x' 'r' 'u' '3.55' 'is s' 'y' '4.22' '3.6' '21.56'
 'i' '6 x' '24.16' '8' 'm' 'ring-type' '10.13' 'is p' '7.43' 'h' '0.82'
 '10.46' '2.77' '2.94' '12.62' '5.15' '19.04' '4.97' '49.21' 'b f' '9.13'
 '1.66' '3.37' '7.21' '3.25' '11.12' '3 x' '4.3' '7.41' '6.21' '8.29'
 '54.78' '20.25' '3.52' '3.04' '2.63' '3.91' '6.44' '8.3' '7.6' '17.44'
 '4.33' '2.82' '6.53' '19.06']
== cap-surface ==
['s' 'h' 'y' 'l' 't' 'e' 'g' nan 'd' 'i' 'w' 'k' '15.94' 'f' 'n' 'r' 'o'
 'a' 'u' 'z' '2.7' 'does l' '5.07' 'p' 'b' 'm' 'cap-diameter' '1.43' 'x'
 '7.14' 'c' 'is h' 'does t' '0.85' '6.57' '12.79' '6.45' '4.66' '23.18'
 '3.06' '16.39' '4.21' 'veil-color' '11.78' '8.1' 'has-ring' 'does h'
 '1.42' 'class' 'has h' 'does None' '10.83' 'season' '8.96' '14.04' '5.73'
 'is None' '24.38' '2.81' '0.88' '2.11' '2.79' 'ring-

In [9]:
test_data = pd.read_csv(DATA / "test.csv")

In [10]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2077964 entries, 0 to 2077963
Data columns (total 21 columns):
 #   Column                Dtype  
---  ------                -----  
 0   id                    int64  
 1   cap-diameter          float64
 2   cap-shape             object 
 3   cap-surface           object 
 4   cap-color             object 
 5   does-bruise-or-bleed  object 
 6   gill-attachment       object 
 7   gill-spacing          object 
 8   gill-color            object 
 9   stem-height           float64
 10  stem-width            float64
 11  stem-root             object 
 12  stem-surface          object 
 13  stem-color            object 
 14  veil-type             object 
 15  veil-color            object 
 16  has-ring              object 
 17  ring-type             object 
 18  spore-print-color     object 
 19  habitat               object 
 20  season                object 
dtypes: float64(3), int64(1), object(17)
memory usage: 332.9+ MB


In [11]:
test_data.isna().sum()

id                            0
cap-diameter                  7
cap-shape                    31
cap-surface              446904
cap-color                    13
does-bruise-or-bleed         10
gill-attachment          349821
gill-spacing             839595
gill-color                   49
stem-height                   1
stem-width                    0
stem-root               1838012
stem-surface            1321488
stem-color                   21
veil-type               1971545
veil-color              1826124
has-ring                     19
ring-type                 86195
spore-print-color       1899617
habitat                      25
season                        0
dtype: int64

In [12]:
for column in test_data.columns[1:]:
    print(f"== {column} ==")
    print(f"{test_data[column].unique()}")

== cap-diameter ==
[ 8.64  6.9   2.   ... 58.98 39.12 46.19]
== cap-shape ==
['x' 'o' 'b' 'f' 's' 'p' 'c' 'g' 't' 'i' 'a' 'n' '7.21' 'e' nan 'w' 'd'
 'k' 'u' 'y' '3.34' '8.3' 'r' 'l' '3.32' '19.76' 'is f' '0.93' '5 f' 'z'
 'p f' 'h' '1.25' 'm' '4.55' 'ring-type' '11.43' '6' '5.59' '4.41' '3.73'
 '3.47' '6.75' '51.63' '6.52' '9.49' '2.7' '3.15' '5.05' 'cap-diameter'
 '4.51' '4.86' '0.97' '3.94' '6.47' '3.23' '2.02' '1.53' '8' '6.15'
 '17.89' '0.74' '4.54']
== cap-surface ==
[nan 't' 'g' 'h' 'd' 'e' 'y' 'k' 's' 'i' 'l' 'w' 'r' 'f' 'o' 'm' 'a' 'n'
 'p' 'b' 'x' 'season' 'u' '6.04' 'z' '10.09' 'spore-print-color' 'c'
 '2.97' 'class' '7.78' '5.05' '5.92' '5.98' '11.96' '7.96' '9.53' '17.98'
 'habitat' '2.47' '20.64' '8.34' 'has-ring' 'does None' '1.95' '16.48'
 '5.84' '5.93' '12.3' '14.18' '4.87' '15.52' '3.49' '6.58' '12.15' '6.7'
 '4.91' '0.94' '2.84' '5.1']
== cap-color ==
['n' 'o' 'y' 'k' 'b' 'w' 'e' 'g' 'p' 'u' 'l' 'r' 'z' 'f' nan 's' 'd' 'i'
 '10.93' 'ring-type' 'a' 'x' '0.73' 'c' 't' 

In [13]:
def outlier_to_nan(data, column, value):
    data.loc[~data[column].isin(value), column] = np.nan

## cap-shape(갓 모양)
- 종모양(bell, b)
- 원뿔모양(conical, c)
- 볼록함(convex, x)
- 평평함(flat, f)
- 둥글게 돌출(knobbed, k)
- 아래로 파임(sunken, s)

In [14]:
train_data["cap-shape"].unique()

array(['f', 'x', 'p', 'b', 'o', 'c', 's', 'd', 'e', 'n', nan, 'w', 'k',
       'l', '19.29', '5 f', 't', 'g', 'z', 'a', '2.85', '7 x', 'r', 'u',
       '3.55', 'is s', 'y', '4.22', '3.6', '21.56', 'i', '6 x', '24.16',
       '8', 'm', 'ring-type', '10.13', 'is p', '7.43', 'h', '0.82',
       '10.46', '2.77', '2.94', '12.62', '5.15', '19.04', '4.97', '49.21',
       'b f', '9.13', '1.66', '3.37', '7.21', '3.25', '11.12', '3 x',
       '4.3', '7.41', '6.21', '8.29', '54.78', '20.25', '3.52', '3.04',
       '2.63', '3.91', '6.44', '8.3', '7.6', '17.44', '4.33', '2.82',
       '6.53', '19.06'], dtype=object)

In [15]:
test_data["cap-shape"].unique()

array(['x', 'o', 'b', 'f', 's', 'p', 'c', 'g', 't', 'i', 'a', 'n', '7.21',
       'e', nan, 'w', 'd', 'k', 'u', 'y', '3.34', '8.3', 'r', 'l', '3.32',
       '19.76', 'is f', '0.93', '5 f', 'z', 'p f', 'h', '1.25', 'm',
       '4.55', 'ring-type', '11.43', '6', '5.59', '4.41', '3.73', '3.47',
       '6.75', '51.63', '6.52', '9.49', '2.7', '3.15', '5.05',
       'cap-diameter', '4.51', '4.86', '0.97', '3.94', '6.47', '3.23',
       '2.02', '1.53', '8', '6.15', '17.89', '0.74', '4.54'], dtype=object)

In [16]:
# 1. 해당 value를 정확하게 가지지 않으면 (is s 허용 x) 모두 결측 처리
cap_shape_value = ['b', 'c', 'x', 'f', 'k', 's']

outlier_to_nan(train_data, "cap-shape", cap_shape_value)
outlier_to_nan(test_data, "cap-shape", cap_shape_value)


In [17]:
print("== train data ==")
print(train_data["cap-shape"].value_counts())
print(f'NaN: {train_data["cap-shape"].isna().sum()}')

== train data ==
cap-shape
x    1436026
f     676238
s     365146
b     318646
c     104520
k         13
Name: count, dtype: int64
NaN: 216356


In [18]:
print("== test data ==")
print(test_data["cap-shape"].value_counts())
print(f'NaN: {test_data["cap-shape"].isna().sum()}')

== test data ==
cap-shape
x    957949
f    452360
s    242698
b    211879
c     69436
k        17
Name: count, dtype: int64
NaN: 143625


## cap-surface
- 섬유질(fibrous, f), 
- 홈이 있는(grooves, g), 
- 비늘이 있는(scaly, y), 
- 매끄러운(smooth, s)

In [19]:
train_data["cap-surface"].unique()

array(['s', 'h', 'y', 'l', 't', 'e', 'g', nan, 'd', 'i', 'w', 'k',
       '15.94', 'f', 'n', 'r', 'o', 'a', 'u', 'z', '2.7', 'does l',
       '5.07', 'p', 'b', 'm', 'cap-diameter', '1.43', 'x', '7.14', 'c',
       'is h', 'does t', '0.85', '6.57', '12.79', '6.45', '4.66', '23.18',
       '3.06', '16.39', '4.21', 'veil-color', '11.78', '8.1', 'has-ring',
       'does h', '1.42', 'class', 'has h', 'does None', '10.83', 'season',
       '8.96', '14.04', '5.73', 'is None', '24.38', '2.81', '0.88',
       '2.11', '2.79', 'ring-type', 'does-bruise-or-bleed', '4.93',
       'spore-print-color', 'spore-color', '2.92', '2.51', '7.99', 'is y',
       '3.64', '3.33', '41.91', '12.2', '8.01', '9.22', '1.14', '6.49',
       '10.34', '10.1', '1.08', 'is k', '0.87'], dtype=object)

In [20]:
test_data["cap-surface"].unique()

array([nan, 't', 'g', 'h', 'd', 'e', 'y', 'k', 's', 'i', 'l', 'w', 'r',
       'f', 'o', 'm', 'a', 'n', 'p', 'b', 'x', 'season', 'u', '6.04', 'z',
       '10.09', 'spore-print-color', 'c', '2.97', 'class', '7.78', '5.05',
       '5.92', '5.98', '11.96', '7.96', '9.53', '17.98', 'habitat',
       '2.47', '20.64', '8.34', 'has-ring', 'does None', '1.95', '16.48',
       '5.84', '5.93', '12.3', '14.18', '4.87', '15.52', '3.49', '6.58',
       '12.15', '6.7', '4.91', '0.94', '2.84', '5.1'], dtype=object)

In [21]:
cap_surface_value = ['f', 'g', 'y', 's']

outlier_to_nan(train_data, "cap-surface", cap_surface_value)
outlier_to_nan(test_data, "cap-surface", cap_surface_value)

In [22]:
print("== train data ==")
print(train_data["cap-surface"].value_counts())
print(f'NaN: {train_data["cap-surface"].isna().sum()}')

print("== test data ==")
print(test_data["cap-surface"].value_counts())
print(f'NaN: {test_data["cap-surface"].isna().sum()}')

== train data ==
cap-surface
s    384970
y    327826
g    263729
f        75
Name: count, dtype: int64
NaN: 2140345
== test data ==
cap-surface
s    257190
y    218336
g    176140
f        54
Name: count, dtype: int64
NaN: 1426244


## cap-color
- 갈색(brown, n), 
- 담황색(buff, b), 
- 시나몬색(cinnamon, c), 
- 회색(gray, g), 
- 초록색(green, r), 
- 핑크색(pink, p), 
- 보라색(purple, u), 
- 빨강색(red, e), 
- 흰색(white, w), 
- 노랑색(yellow, y)

In [23]:
train_data["cap-color"].unique()

array(['u', 'o', 'b', 'g', 'w', 'n', 'e', 'y', 'r', 'p', 'k', 'l', 'i',
       'h', 'd', 's', 'a', 'f', '2.05', 'season', 'c', 'x', '13', '7.72',
       'm', 'z', '6.76', '7.15', 't', 'ring-type', nan, 'class', '12.89',
       '8.83', '24.75', '22.38', '1.51', '10.1', '17.94', '3.57',
       'does n', '4.89', '6.2', '21.53', '6.41', '4.98', '3.95',
       'does-bruise-or-bleed', '6.59', '5.25', 'veil-color', '6.9',
       '5.41', '11.13', '3.11', '2.57', '17.93', '2.7', '8.57', '11.92',
       '3.08', '2.82', '4.24', '17.19', '3.34', '7', '2.9', '6.36',
       '5.91', '10.56', '26.89', '4. n', '20.62', 'stem-surface', '20.02',
       '20', '25.98', '8.67', '9.02'], dtype=object)

In [24]:
test_data["cap-color"].unique()

array(['n', 'o', 'y', 'k', 'b', 'w', 'e', 'g', 'p', 'u', 'l', 'r', 'z',
       'f', nan, 's', 'd', 'i', '10.93', 'ring-type', 'a', 'x', '0.73',
       'c', 't', '19.18', 'h', '5.35', 'm', '21.38', 'has-ring', '5.38',
       'class', '7.41', '18.49', 'habitat', '5.16', '4.5', '4.75',
       '17.01', '3.0', '24.74', '12.91', '4.11', '4.92', '10.83', '1.83',
       '2.51', '6.74', '4.18', '23.96',
       'cap---------------------------------------------------------------------------------root',
       '4.96', '0.91', 'season', '6.18', '4.61', '9.19'], dtype=object)

In [25]:
cap_color_value = ['n', 'b', 'c', 'g', 'r', 'p', 'u', 'e', 'w', 'y']

outlier_to_nan(train_data, "cap-color", cap_color_value)
outlier_to_nan(test_data, "cap-color", cap_color_value)

In [26]:
print("== train data ==")
print(train_data["cap-color"].value_counts())
print(f'NaN: {train_data["cap-color"].isna().sum()}')

print("== test data ==")
print(test_data["cap-color"].value_counts())
print(f'NaN: {test_data["cap-color"].isna().sum()}')

== train data ==
cap-color
n    1359542
y     386627
w     379442
g     210825
e     197290
p      91838
r      78236
u      73172
b      61313
c         14
Name: count, dtype: int64
NaN: 278646
== test data ==
cap-color
n    904307
y    259062
w    253844
g    140681
e    131524
p     61186
r     51784
u     48865
b     40790
c        12
Name: count, dtype: int64
NaN: 185909


## does-bruise-or-bleed
- 멍이나 피가 남(true, t), 
- 멍이나 피가 나지않음(false, f)

In [27]:
train_data["does-bruise-or-bleed"].unique()

array(['f', 't', 'd', 'has-ring', 'w', 'o', 'b', 'x', 'p', nan, 'g', 'y',
       'r', 'a', 'l', 'i', 'c', 'n', 'z', 's', 'k', 'h', '3.43', 'e',
       '4.42', '2.9', 'u'], dtype=object)

In [28]:
test_data["does-bruise-or-bleed"].unique()

array(['t', 'f', 'c', 'k', 'season', 'does t', nan, 'x', 's', 'a', 'p',
       'n', 'o', 'w', 'b', 'i', 'e', 'r', 'l', 'y', 'm', 'g', 'h'],
      dtype=object)

In [29]:
bruise_or_bleed_value = ['t', 'f']

outlier_to_nan(train_data, "does-bruise-or-bleed", bruise_or_bleed_value)
outlier_to_nan(test_data, "does-bruise-or-bleed", bruise_or_bleed_value)

In [31]:
print("== train data ==")
print(train_data["does-bruise-or-bleed"].value_counts())
print(f'NaN: {train_data["does-bruise-or-bleed"].isna().sum()}')

print("== test data ==")
print(test_data["does-bruise-or-bleed"].value_counts())
print(f'NaN: {test_data["does-bruise-or-bleed"].isna().sum()}')

== train data ==
does-bruise-or-bleed
f    2569743
t     547085
Name: count, dtype: int64
NaN: 117
== test data ==
does-bruise-or-bleed
f    1713662
t     364227
Name: count, dtype: int64
NaN: 75


## gill-attachment
- attached(붙음)=a, 
- descending(내림)=d, 
- free(자유)=f, 
- notched(톱니)=n

In [32]:
train_data["gill-attachment"].unique()

array(['a', 'x', 's', 'd', 'e', nan, 'f', 'p', 'l', 'm', 'b', '32.54',
       'n', 'g', 'i', 'u', 'does-bruise-or-bleed', 't', 'o', 'c', 'w',
       '4.64', 'k', 'r', '4.77', 'h', 'p p', '7.92', 'z', 'season', 'y',
       '8.79', 'does None', 'has f', 'ring-type', '16.33', '10.85',
       '20.07', '2.82', '7.86', '3.91', 'does', '10.23', '6.74', '0.92',
       '3.45', '1', 'is a', '3.71', '50.44', '11.62', 'has d', '1.32',
       '8.47', '6.11', '2.41', '2.54', '6.32', '19.65', '15.49', '4.01',
       '8.37', 'does f', '28.7', '13.15', '1.37', '28.15', '7.09', '9.88',
       '2.67', '18.21', '1.48', '5.93', '1.51', '16.27', '11.26', '2.79',
       'is f', '13.94'], dtype=object)

In [33]:
test_data["gill-attachment"].unique()

array([nan, 's', 'p', 'x', 'f', 'a', 'd', 'e', 'c', 't', 'i', 'u',
       '13.42', 'k', '6.24', 'n', 'w', 'm', 'class', 'z', 'l', '8.33',
       'b', 'o', 'g', '2.75', '0.95', 'r', 'season', 'spore-print-color',
       '1.75', 'y', 'h', '3.7', '23.73', '1.58', '1.32', '12.22', '6.35',
       '17.77', '1.26', '7.18', '8.21', '2.51', '6.11', '17.11', '10.62',
       '0.93', '25.92', '4.8', 'e s', '29.82', '1.56', '8.1', '0.88',
       '11.8', '17.97', '12.99', '23.18', '22.33', '2.86', 'has-ring',
       '1.83', '0.87', '2.17', '2.82', 'is None'], dtype=object)

In [34]:
gill_attachment_value = ['a', 'd', 'f', 'n']

outlier_to_nan(train_data, "gill-attachment", gill_attachment_value)
outlier_to_nan(test_data, "gill-attachment", gill_attachment_value)

In [35]:
print("== train data ==")
print(train_data["gill-attachment"].value_counts())
print(f'NaN: {train_data["gill-attachment"].isna().sum()}')

print("== test data ==")
print(test_data["gill-attachment"].value_counts())
print(f'NaN: {test_data["gill-attachment"].isna().sum()}')

== train data ==
gill-attachment
a    646034
d    589236
f    119953
n        20
Name: count, dtype: int64
NaN: 1761702
== test data ==
gill-attachment
a    430960
d    392584
f     79630
n        13
Name: count, dtype: int64
NaN: 1174777


## gill-spacing
- close(가깝게)=c, 
- crowded(밀집)=w, 
- distant(떨어짐)=d

In [36]:
train_data["gill-spacing"].unique()

array(['c', nan, 'd', 'f', 'x', 'b', 'a', '3.61', '2.69', 'k', '4.8', 'e',
       'y', 'class', 's', '9.01', 'p', '3.92', '5.22', '6.67', '4.04',
       't', '0.73', 'i', '3.57', '24.38', 'w', 'h', 'cap-surface', 'l',
       '1', '12.27', '5.42', 'r', '1.6', 'n', 'g', '0', '3.81', '4.09',
       '1.36', '3.24', '5.55', '5.7', '3.62', 'does f', '6.4', '1.88',
       '55.13'], dtype=object)

In [37]:
test_data["gill-spacing"].unique()

array([nan, 'c', 'f', 'd', 's', 'e', 'has f', 'a', 'y', 'm', 'w', 'b',
       'g', 'p', 'x', '1.61', 'r', '1.46', '2.93', 't', '3.42', 'i', 'k',
       'does c', '2.98', '6.52', '13.66', '0.73', 'does None', '1.64',
       '2.44', '4.92', '1.68', '2.7', '5', '18.89'], dtype=object)

In [38]:
gill_spacing_value = ['c', 'w', 'd']

outlier_to_nan(train_data, "gill-spacing", gill_spacing_value)
outlier_to_nan(test_data, "gill-spacing", gill_spacing_value)

In [39]:
print("== train data ==")
print(train_data["gill-spacing"].value_counts())
print(f'NaN: {train_data["gill-spacing"].isna().sum()}')

print("== test data ==")
print(test_data["gill-spacing"].value_counts())
print(f'NaN: {test_data["gill-spacing"].isna().sum()}')

== train data ==
gill-spacing
c    1331054
d     407932
w          1
Name: count, dtype: int64
NaN: 1377958
== test data ==
gill-spacing
c    886976
d    272085
w         4
Name: count, dtype: int64
NaN: 918899


## gill-color
- black(검정)=k,
- brown(갈색)=n,
- buff(담황색)=b,
- chocolate(초콜릿색)=h,
- gray(회색)=g,
- green(녹색)=r,
- orange(주황색)=o,
- pink(분홍색)=p,
- purple(보라색)=u,
- red(빨강색)=e,
- white(흰색)=w,
- yellow(노랑색)=y

In [40]:
train_data["gill-color"].unique()

array(['w', 'n', 'g', 'k', 'y', 'f', 'p', 'o', 'b', 'u', 'e', 'r', 'd',
       't', '3.45', 'z', '5', '3.39', 'season', 'h', 'x', 's', '4',
       'class', 'c', 'm', 'spacing', '0.92', nan, '18.12', 'l', 'does w',
       'a', '7.59', '8.06', '6.19', 'has-ring', '4.49', '9.46', '5.01',
       'ring-type', '3.4', 'i', '17', '10.07', 'stem-root', '20.6',
       'spore-print-color', '18.03', 'does-bruise-or-bleed', '8.83',
       'habitat', '10.21', '4.64', '6.4', 'is y', 'e y', '1.91', 'does n',
       '16.41', '6.41', 'veil-type', '20.44', '8.37'], dtype=object)

In [41]:
test_data["gill-color"].unique()

array(['w', 'y', 'n', 'e', 'f', 'b', 'g', 'p', 'o', 'u', 'k', 'r', 'l',
       'd', nan, 'has-ring', 'season', 't', 's', 'a', 'x', 'c', '8.95',
       'i', '6.3', 'h', '1.55', '19.46', 'spacing', 'z', 'class', '5.01',
       '10.56', '12.87', 'is w', 'does-bruise-or-bleed', '17.26', '18',
       'spore-print-color', 'ring-type', 'does f', '7.07', '3.38', 'm',
       '8.53', '18.05', 'habitat', '2.6', '7.81', 'has g', '9.69', '4',
       '10.34', '21.87', '9.41', '4.78', '2.83'], dtype=object)

In [42]:
gill_color_value = ['k', 'n', 'b', 'h', 'g', 'r', 'o', 'p', 'u', 'e', 'w', 'y']

outlier_to_nan(train_data, "gill-color", gill_color_value)
outlier_to_nan(test_data, "gill-color", gill_color_value)

In [43]:
print("== train data ==")
print(train_data["gill-color"].value_counts())
print(f'NaN: {train_data["gill-color"].isna().sum()}')

print("== test data ==")
print(test_data["gill-color"].value_counts())
print(f'NaN: {test_data["gill-color"].isna().sum()}')

== train data ==
gill-color
w    931538
n    543386
y    469464
p    343626
g    212164
o    157119
k    127970
r     62799
e     56047
b     47247
u     45399
h        24
Name: count, dtype: int64
NaN: 120162
== test data ==
gill-color
w    620773
n    362169
y    313932
p    229155
g    141519
o    105048
k     85360
r     41499
e     37432
b     31183
u     30084
h        13
Name: count, dtype: int64
NaN: 79797


## stem-root(원본 데이터 stalk-root)
- bulbous(둥근형)=b, 
- club(곤봉형)=c, 
- cup(컵형)=u, 
- equal(평형)=e, 
- rhizomorphs(근형)=z, 
- rooted(뿌리형)=r

In [44]:
train_data["stem-root"].unique()

array([nan, 'b', 'c', 'r', 's', 'f', '5.59', '2.77', '20.01', 'y', 'o',
       'k', 'd', 'n', 'w', 'u', 'p', 'x', 'i', '10.87', 'a', '3.63', 't',
       'm', 'l', 'h', 'g', '16.88', '15.69', '1.48', '3.23', 'e', '20.0',
       '18.06', 'z', 'spore-print-color', '3.49', '13.03', '7.15'],
      dtype=object)

In [45]:
test_data["stem-root"].unique()

array(['b', nan, 's', 'r', 'c', 'f', 'a', 'p', 'u', 'o', 'x', 't', 'e',
       'w', 'g', '1.48', 'k', 'd', 'y', '1.62', '18.29', 'm', 'l', 'h',
       'n', 'i', '3.24', '13.46', 'z', '2.82', '3.59', '24.73'],
      dtype=object)

In [46]:
stem_root_value = ['b', 'c', 'u', 'e', 'z', 'r']

outlier_to_nan(train_data, "stem-root", stem_root_value)
outlier_to_nan(test_data, "stem-root", stem_root_value)

In [47]:
print("== train data ==")
print(train_data["stem-root"].value_counts())
print(f'NaN: {train_data["stem-root"].isna().sum()}')

print("== test data ==")
print(test_data["stem-root"].value_counts())
print(f'NaN: {test_data["stem-root"].isna().sum()}')

== train data ==
stem-root
b    165801
r     47803
c     28592
u         8
e         6
z         2
Name: count, dtype: int64
NaN: 2874733
== test data ==
stem-root
b    110581
r     31606
c     19025
u         8
e         7
z         2
Name: count, dtype: int64
NaN: 1916735


## stem-surface (원본데이터 고리 아래의 줄기)

- fibrous(섬유질)=f
- scaly(비늘형)=y
- silky(비단질)=k
- smooth(매끈형)=s

In [48]:
train_data["stem-surface"].unique()

array([nan, 'y', 's', 't', 'g', 'h', 'k', 'i', 'f', 'l', 'd', 'x',
       '12.04', 'w', 'a', 'o', 'c', 'n', 'm', 'e', 'p', 'z', '6.58',
       '4.34', 'b', '3.89', 'r', '25.83', '1.59', '0.0', '5.97', '5.81',
       'u', 'season', '10.48', '3.68', '5.56', '4.41', '5.48', '5.51',
       'class', 'has-ring', '13.1', '17.46', '5.35', '7.23', 'does None',
       '1.03', 'does s', '7.45', 'has h', 'does-bruise-or-bleed', '1.94',
       '49.46', '19.35', '2.68', '4.74', 'spore-print-color', '10.93',
       '24.12', '13.94'], dtype=object)

In [49]:
test_data["stem-surface"].unique()

array([nan, 's', 'g', 'y', 't', 'i', 'k', 'h', 'f', 'w', 'l', 'r', 'd',
       'e', '2.98', 'b', 'c', 'does None', '6.06', 'u', 'o', '2.95',
       'season', '6.18', 'p', 'class', '32.6', 'n', 'a', '32.63', 'x',
       'm', '9.98', 'cap-diameter', '2.73', '15.25', '5.57', '15.55',
       '18.35', '3.24', '6.12', '13.09', '4.76', '35.38', 'sp', 'z',
       '6.51', '8.73', '10.14', '13.01', '15.51', 'does-bruise-or-bleed',
       '11.53', '4.54', '6.59'], dtype=object)

In [50]:
stem_surface_value = ['f', 'y', 'k', 's']

outlier_to_nan(train_data, "stem-surface", stem_surface_value)
outlier_to_nan(test_data, "stem-surface", stem_surface_value)

In [51]:
print("== train data ==")
print(train_data["stem-surface"].value_counts())
print(f'NaN: {train_data["stem-surface"].isna().sum()}')

print("== test data ==")
print(test_data["stem-surface"].value_counts())
print(f'NaN: {test_data["stem-surface"].isna().sum()}')

== train data ==
stem-surface
s    327610
y    255500
k     73383
f       512
Name: count, dtype: int64
NaN: 2459940
== test data ==
stem-surface
s    218496
y    169462
k     49075
f       310
Name: count, dtype: int64
NaN: 1640621


## stem-color(원본 데이터 고리 아래의 줄기)
-  brown(갈색)=n
-  buff(담황색)=b
-  cinnamon(계피색)=c
-  gray(회색)=g
-  orange(주황색)=o
-  pink(분홍색)=p
-  red(빨강색)=e
-  white(흰색)=w
-  yellow(노랑색)=y

In [52]:
train_data["stem-color"].unique()

array(['w', 'o', 'n', 'y', 'e', 'u', 'p', 'f', 'g', 'r', 'k', 'l', 'b',
       '3.13', 't', 'z', 'a', 'h', 'd', nan, 's', '7.33', 'is n', 'i',
       'c', 'x', 'e n', '1.75', 'm', '33.52', 'ring-type', '2.78',
       'spore-print-color', '23.59', '8.32', 'is w', '26.4', '4.75',
       '7.84', 'class', '2.75', '8.49', '4.49', '1.41', '17.45', '3.53',
       '12.92', '3.98', '20.07', '7.7', '22.6', '6.31', '6.09', '3.56',
       '3.37', '4.62', '2.54', '39.51', '18.06', '4.33'], dtype=object)

In [53]:
test_data["stem-color"].unique()

array(['w', 'n', 'y', 'g', 'o', 'p', 'u', 'e', 'k', 'r', 'l', 'b', 's',
       'f', nan, 'h', 'x', 'a', '3.05', 't', 'stem-root', 'veil-color',
       'm', 'c', 'd', '7.35', '8.04', '6.58', 'veil-type', '17.16',
       'season', '2.96', '17.49', 'i', 'z', '10.6', '11.31', '5.5',
       'ring-type', '11.0', '8.09', '10.93', '6.67', '6.99', '5.61',
       '6.93', 'does-bruise-or-bleed', '6.28', '2.84', '7.71',
       'spore-print-color', 'class', '3.66', '3.8', 'habitat', '3.02'],
      dtype=object)

In [54]:
stem_color_value = ['n', 'b', 'c', 'g', 'o', 'p', 'e', 'w', 'y']

outlier_to_nan(train_data, "stem-color", stem_color_value)
outlier_to_nan(test_data, "stem-color", stem_color_value)

In [55]:
print("== train data ==")
print(train_data["stem-color"].value_counts())
print(f'NaN: {train_data["stem-color"].isna().sum()}')

print("== test data ==")
print(test_data["stem-color"].value_counts())
print(f'NaN: {test_data["stem-color"].isna().sum()}')

== train data ==
stem-color
w    1196637
n    1003464
y     373971
g     132019
o     111541
e     103373
p      54690
b       7365
c          7
Name: count, dtype: int64
NaN: 133878
== test data ==
stem-color
w    797365
n    668156
y    250141
g     88202
o     75094
e     68804
p     36356
b      4895
c         8
Name: count, dtype: int64
NaN: 88943


## veil-type
- partial(부분적)=p
- universal(전면적)=u

In [56]:
train_data["veil-type"].unique()

array([nan, 'u', 'd', 'a', 'h', '21.11', 'g', 'c', 'e', 'y', 'i', 'f',
       'is None', 't', 'w', 'p', 'b', 's', 'k', 'r', 'l', 'n', '5.94'],
      dtype=object)

In [57]:
test_data["veil-type"].unique()

array(['u', nan, 'l', 'e', 'y', 'w', 'p', 'g', 'k', 'a', 's', 'c', 'b',
       'n', '11', 'm'], dtype=object)

In [58]:
veil_type_value = ['p', 'u']

outlier_to_nan(train_data, "veil-type", veil_type_value)
outlier_to_nan(test_data, "veil-type", veil_type_value)

In [59]:
print("== train data ==")
print(train_data["veil-type"].value_counts())
print(f'NaN: {train_data["veil-type"].isna().sum()}')

print("== test data ==")
print(test_data["veil-type"].value_counts())
print(f'NaN: {test_data["veil-type"].isna().sum()}')

== train data ==
veil-type
u    159373
p         2
Name: count, dtype: int64
NaN: 2957570
== test data ==
veil-type
u    106373
p         3
Name: count, dtype: int64
NaN: 1971588


## veil-color
- brown(갈색)=n
- orange(주황색)=o
- white(흰색)=w
- yellow(노랑색)=y

In [60]:
train_data["veil-color"].unique()

array([nan, 'n', 'w', 'k', 'y', 'e', 'u', 'p', 'd', 'g', 'r', 'h', 's',
       '8.25', 't', 'c', 'o', 'i', '2.49', 'f', 'a', 'b', 'l', 'z',
       '3.32'], dtype=object)

In [61]:
test_data["veil-color"].unique()

array(['w', nan, 'n', 'y', 'e', 'u', 'k', 'i', 'p', 'g', 'r', 'f', 'b',
       'h', 's', 't', '4.02', 'o', 'd', 'm', 'l', '9', 'c', 'a'],
      dtype=object)

In [62]:
veil_color_value = ['n', 'o', 'w', 'y']

outlier_to_nan(train_data, "veil-color", veil_color_value)
outlier_to_nan(test_data, "veil-color", veil_color_value)

In [63]:
print("== train data ==")
print(train_data["veil-color"].value_counts())
print(f'NaN: {train_data["veil-color"].isna().sum()}')

print("== test data ==")
print(test_data["veil-color"].value_counts())
print(f'NaN: {test_data["veil-color"].isna().sum()}')

== train data ==
veil-color
w    279070
y     30473
n     30039
o        13
Name: count, dtype: int64
NaN: 2777350
== test data ==
veil-color
w    186432
y     20782
n     20256
o         5
Name: count, dtype: int64
NaN: 1850489


## has-ring
- 고리있음 (true, t)
- 고리 없음 (false, f)

In [64]:
train_data["has-ring"].unique()

array(['f', 't', 'h', 'r', 'y', 'c', 'e', 'g', 'l', 's', nan, 'p', 'x',
       'k', 'z', 'f has-ring', 'd', 'o', 'n', 'm', 'i', '10.3', 'w', 'a'],
      dtype=object)

In [65]:
test_data["has-ring"].unique()

array(['t', 'f', nan, 'u', 'a', 'c', 'l', 'g', 'i', 'm', 'p', 'r', 'x',
       'y', 'd', 'e', 'z', 'k', 'o', 'h', 'b', 's', 'w', '20.96'],
      dtype=object)

In [66]:
has_ring_value = ['t', 'f']

outlier_to_nan(train_data, "has-ring", has_ring_value)
outlier_to_nan(test_data, "has-ring", has_ring_value)

In [67]:
print("== train data ==")
print(train_data["has-ring"].value_counts())
print(f'NaN: {train_data["has-ring"].isna().sum()}')

print("== test data ==")
print(test_data["has-ring"].value_counts())
print(f'NaN: {test_data["has-ring"].isna().sum()}')

== train data ==
has-ring
f    2368820
t     747982
Name: count, dtype: int64
NaN: 143
== test data ==
has-ring
f    1578092
t     499759
Name: count, dtype: int64
NaN: 113


## ring-type (NaN을 None으로 볼 것인가? => 일단 n과 NaN은 따로)
- cobwebby(거미줄)=c
- evanescent(덧없음)=e
- flaring(펼침)=f
- large(크기 큼)=l
- none(없음)=n
- pendant(늘어짐)=p
- sheathing(덮개형)=s
- zone(대칭형)=z

In [68]:
train_data["ring-type"].unique()

array(['f', 'z', 'e', nan, 'p', 'l', 'g', 'r', 'm', 'y', 'h', 'o', 't',
       'ring-type', 'a', 'd', 's', 'x', '4', 'b', '15', 'u', 'n', 'w',
       'does f', '3.12', 'i', 'season', 'k', 'c', 'does-bruise-or-bleed',
       '11', '23.6', '1', '14', '2', 'spore-print-color', 'class', 'sp',
       '2.87', '8.25'], dtype=object)

In [69]:
test_data["ring-type"].unique()

array(['g', 'f', 'z', nan, 'r', 'e', 'l', 'p', 'm', 'd', 'n', 'u', 's',
       'season', 'k', 't', 'a', 'y', 'o', 'c', 'w', '1', 'x', 'b', 'h',
       'ring-type', 'i', '3.48', 'is p', '12.63', '10.36', '8.12',
       'does f', '18.5', '9.33', 'spore-print-color', '2'], dtype=object)

In [70]:
ring_type_value = ['c', 'e', 'f', 'l', 'n', 'p', 's', 'z']

outlier_to_nan(train_data, "ring-type", ring_type_value)
outlier_to_nan(test_data, "ring-type", ring_type_value)

In [71]:
print("== train data ==")
print(train_data["ring-type"].value_counts())
print(f'NaN: {train_data["ring-type"].isna().sum()}')

print("== test data ==")
print(test_data["ring-type"].value_counts())
print(f'NaN: {test_data["ring-type"].isna().sum()}')

== train data ==
ring-type
f    2477170
e     120006
z     113780
l      73443
p      67678
n         34
s         18
c         11
Name: count, dtype: int64
NaN: 264805
== test data ==
ring-type
f    1650200
e      80348
z      75917
l      48847
p      45654
n         16
c         13
s         12
Name: count, dtype: int64
NaN: 176957


## spore-print-color
- black(검정)=k
- brown(갈색)=n
- buff(담황색)=b
- chocolate(초콜릿색)=h
- green(녹색)=r
- orange(주황색)=o
- purple(보라색)=u
- white(흰색)=w
- yellow(노랑색)=y

In [72]:
train_data["spore-print-color"].unique()

array([nan, 'k', 'w', 'p', 'n', 'r', 'u', 'g', 't', 'f', 'd', 'l', 'y',
       'a', 's', '2.49', 'e', 'o', 'c', 'b', '10 None', 'h', 'x',
       '9 None', 'i', 'm', 'veil-color', 'class', '2.62', 'season',
       '9.55', '6.36', '4.58'], dtype=object)

In [73]:
test_data["spore-print-color"].unique()

array([nan, 'p', 'k', 'w', 'n', 'r', 'g', 'u', 'b', 'o', 'f', 't', 'e',
       'h', 'veil-color', 'd', 'l', 'i', 's', 'y', 'a', '17.72', '2.52',
       '8.82', '6.14', 'c', '27.48', 'ring-type', 'z', 'x', '26.48',
       '3.65', '4', '2.92'], dtype=object)

In [74]:
spore_print_color_value = ['k', 'n', 'b', 'h', 'r', 'o', 'u', 'w', 'y']

outlier_to_nan(train_data, "spore-print-color", spore_print_color_value)
outlier_to_nan(test_data, "spore-print-color", spore_print_color_value)

In [75]:
print("== train data ==")
print(train_data["spore-print-color"].value_counts())
print(f'NaN: {train_data["spore-print-color"].isna().sum()}')

print("== test data ==")
print(test_data["spore-print-color"].value_counts())
print(f'NaN: {test_data["spore-print-color"].isna().sum()}')

== train data ==
spore-print-color
k    107310
w     50173
n     22646
r      7975
u      7256
y        36
b         5
o         3
h         3
Name: count, dtype: int64
NaN: 2921538
== test data ==
spore-print-color
k    71573
w    33657
n    15081
r     5305
u     4845
y       18
o        8
b        7
h        3
Name: count, dtype: int64
NaN: 1947467


## habitat
- grasses(풀)=g
- leaves(잎)=l 
- meadows(목초지)=m
- paths(길)=p
- urban(도시)=u
- waste(황무지)=w
- woods(숲)=d 

In [76]:
train_data["habitat"].unique()

array(['d', 'l', 'g', 'h', 'p', 'm', 'u', 'w', 'y', nan, 'n', 'a', 's',
       'k', 'habitat', 'z', '8.09', '17.1', 'b', 't', 'c', '9.28',
       'ring-type', 'e', 'r', 'does-bruise-or-bleed', 'f', 'is w', 'o',
       '2.94', 'x', '4', 'is h', '5.56', 'class', 'i', '10.07', '7.31',
       '5.62', 'spore-print-color', 'cap-diameter', '3.11', '16.46',
       '7.37', 'veil-type', '17.38', '1.66', '6.63', '18.35', '6.75',
       '2.44', '3.68', '2.25'], dtype=object)

In [77]:
test_data["habitat"].unique()

array(['d', 'p', 'u', 'g', 'h', 'm', 'l', 'w', 's', 't', 'habitat', 'k',
       nan, 'n', 'x', 'o', 'e', 'a', 'spore-print-color', 'class', 'c',
       'b', 'y', 'r', '4.58', '4.76', 'has-ring', '19.85', 'f', '2.53',
       '9.01', '2.02', '5.84', '7.01', 'i', '5.92', '5.83', 'z', '1.75',
       '3.19'], dtype=object)

In [78]:
habitat_value = ['g', 'l', 'm', 'p', 'u', 'w', 'd']

outlier_to_nan(train_data, "habitat", habitat_value)
outlier_to_nan(test_data, "habitat", habitat_value)

In [79]:
print("== train data ==")
print(train_data["habitat"].value_counts())
print(f'NaN: {train_data["habitat"].isna().sum()}')

print("== test data ==")
print(test_data["habitat"].value_counts())
print(f'NaN: {test_data["habitat"].isna().sum()}')

== train data ==
habitat
d    2177573
g     454908
l     171892
m     150969
w      18530
p      17180
u       5264
Name: count, dtype: int64
NaN: 120629
== test data ==
habitat
d    1450420
g     304300
l     114458
m     101258
w      12324
p      11429
u       3434
Name: count, dtype: int64
NaN: 80341


In [83]:
train_data.to_csv("train_outlier_preprocessing.csv", index=False)
test_data.to_csv("test_outlier_preprocessing.csv", index=False)